<% If True Then %>
	<table style="border:0px solid green; background-color:blue;"  align='center' width=<%=PageWidth%>>		<% ' Start Table Footer 1 %>

	<tr>
		<td align="center">
		<table align="center"><tr><td>
		<%
		If TRUE Then 
		%>
		<!-- 
		Suckerfish drop-down menus ...
		#INCLUDE VIRTUAL = "/Misc/Navbars/navbar1bFooter.inc.asp"
		--> 
		<% End If %>
		</td></tr></table>

		<XXXimg align="center" src="https://www.starlite-intl.com/Images/bottompage2.GIF" height="43px">
		</td>
	</tr>

	</table>	<% ' End Table Footer 1 %>   

	<span style="text-decoration:none;font-size:8pt;">
	<br>Website by IntelliGineering.com   
	<br><br>
	<form action="https://www.starlite-intl.com/mobile1" method='GET'>
	<input type=submit value="Mobile Site">
	</form>
	</span>

	<br><br>  	   
<% End If %>