vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|20 Nov 2006 23:43:30 -0000
vti_timecreated:TR|26 Feb 2006 19:52:55 -0000
vti_lineageid:SR|{E7381FD4-0743-4998-9CB2-CA41BC8220DD}
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|26 Feb 2006 14:52:55 -0500
vti_cacheddtm:TX|26 Feb 2006 19:52:55 -0000
vti_filesize:IR|3598
