vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Apr 2005 19:13:40 -0000
vti_extenderversion:SR|5.0.2.6790
vti_title:SR|Starlite International LLC - Online Store
vti_lineageid:SR|{E5A2B6EE-689F-42D8-A883-A9BB95A29369}
vti_backlinkinfo:VX|eds/SCART.ASP
vti_cacheddtm:TX|14 Apr 2005 19:13:40 -0000
vti_filesize:IR|6167
vti_cachedtitle:SR|Starlite International LLC - Online Store
vti_cachedbodystyle:SR|<body background="../Images/background.jpg" bgcolor="#FFFFFF"  link="#000000" vlink="#000000" topmargin="0" leftmargin="0"  marginwidth="0" marginheight="0">
vti_cachedlinkinfo:VX|S|../Images/background.jpg S|../Images/toptitle.jpg S|../Images/emptynav.jpg S|../Images/bottitle.JPG S|../Images/leftbar.gif S|../Images/blanka1.gif S|../Images/can1.gif S|../Images/USA1.gif S|../images/arrow2.gif H|./scart.asp S|../images/arrow2.gif H|./scart.asp S|../images/arrow2.gif H|./Service.asp K|SCART.ASP S|../Images/bottompage.GIF
vti_cachedsvcrellinks:VX|FSUS|Images/background.jpg FSUS|Images/toptitle.jpg FSUS|Images/emptynav.jpg FSUS|Images/bottitle.JPG FSUS|Images/leftbar.gif FSUS|Images/blanka1.gif FSUS|Images/can1.gif FSUS|Images/USA1.gif FSUS|images/arrow2.gif FHUS|eds/scart.asp FSUS|images/arrow2.gif FHUS|eds/scart.asp FSUS|images/arrow2.gif NHUS|eds/Service.asp FKUS|eds/SCART.ASP FSUS|Images/bottompage.GIF
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|keywords GPS,Navigation,Garmin,CB-Radios,Uniden,Cobra,Motorola,2-way\\ radios,Hand-tools,Pyramid\\  description Online\\ store\\ for\\ GPS\\ Global\\ Positioning\\ Systems,\\ Navigation\\ equipment,\\ CB\\ Radios,\\ FRS\\ Radios,\\ GMRS\\ Radios,\\ Antennas,\\ Car\\ Audio,\\ Hand\\ Tools.\\ \\ Shopping\\ on\\ a\\ secure\\ SSL\\ line.\\ Accepting\\ Visa,\r\nMastercard,\\ American\\ Express\\ cards. Author \\ IAC\\ @\\ www.ontbiz.com/iac\\ -\\ Designed\\ and\\ Programmed\\ by\\ Anyperson.Com\\ www.anyperson.com/tds
vti_charset:SR|windows-1252
