


<table border="1" bordercolor="green" cellpadding="5" style="text-align: left; margin-left: auto; margin-right: auto; width: 85%;">


<tbody><tr>
    <td align="center"><span style="font-family: helvetica,arial,sans-serif;">
    We also do eCommerce website design. 
    Your first year of web hosting is </span><font color="brown" style="font-family: helvetica,arial,sans-serif;">FREE</font><span style="font-family: helvetica,arial,sans-serif;">.
    </span><a href="mailto:starlite@starlite-intl.com" style="font-family: helvetica,arial,sans-serif;">Email us</a><span style="font-family: helvetica,arial,sans-serif;"> for details.</span>
    </td>
</tr><tr align="center">
      <td style="vertical-align: top;"><a href="http://www.starlite-intl.com/scart/scart.asp?sar=Certificates&amp;area=Gift%20Certificates&amp;sid=257"><img src="https://www.starlite-intl.com/imi/GCAD.jpg" title="" alt="" style="border: 0px solid ; width: 170px; height: 85px;"></a><br>
      </td>
    </tr>


</tbody>
</table>   
