vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:12:47 -0000
vti_timecreated:TR|05 Mar 2006 23:57:43 -0000
vti_lineageid:SR|{0E65E489-B8F6-4F3E-AFE8-3A23498506A1}
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|05 Mar 2006 23:57:43 -0000
vti_cacheddtm:TX|05 Mar 2006 23:57:43 -0000
vti_filesize:IR|41595
