vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:12:47 -0000
vti_timecreated:TR|05 Mar 2006 23:57:45 -0000
vti_title:SR|Star Lite Intl. - GPS, GPS Sensors, GPS accessories, CB radios, 2-way radios, Marine electronics, Flash memory, Scanners, MP3, audio/video, hand tools
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{0FFAE9BD-D955-4F26-85CA-9455C551E23E}
vti_backlinkinfo:VX|SCART/BKPs/Dead/Bkp.060305/11102005SCART.ASP
vti_nexttolasttimemodified:TR|05 Mar 2006 23:57:45 -0000
vti_cacheddtm:TX|05 Mar 2006 23:57:45 -0000
vti_filesize:IR|6660
vti_cachedtitle:SR|Star Lite Intl. - GPS, GPS Sensors, GPS accessories, CB radios, 2-way radios, Marine electronics, Flash memory, Scanners, MP3, audio/video, hand tools
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" link="#000000" vlink="#000000" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0">
vti_cachedlinkinfo:VX|Q|../Misc/StyleSheet1.css S|../Images/can1.gif S|../Images/USA1.gif K|11102005SCART.ASP
vti_cachedsvcrellinks:VX|NQUS|SCART/BKPs/Dead/Misc/StyleSheet1.css NSUS|SCART/BKPs/Dead/Images/can1.gif NSUS|SCART/BKPs/Dead/Images/USA1.gif FKUS|SCART/BKPs/Dead/Bkp.060305/11102005SCART.ASP
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|keywords gps,\\ gps\\ navigation,\\ gps\\ sensors,\\ OEM\\ gps,\\ GPS\\ accessories,\\ cb,\\ CB\\ radio,\\ cb\\ radios,\\ garmin\\ gps,\\ global\\ positioning,\\ WalkyTalky,\\ mobile\\ tracking,\\ fleet\\ tracking,\\ usglobasat\\ gps,\\ bluetooth,\\ flash\\ memory,\\ gmrs,\\ marine\\ radios,\\ navigation\\ electronics,\\ 2-way\\ radios,\\ radio\\ scanners,\\ marine\\ radios,\\ car\\ audio,\\ car\\ stereos,\\ power\\ amplifiers,\\ antennas,\\ power\\ supplies,\\ regulated\\ power\\ supplies,\\ dj,\\ accessories,\\ mechanics\\ tools,\\ hand\\ tools,\\ uniden,\\ cobra,\\ midland,\\ mit,\\ pyramid,\\ pyle,\\ solarcon description Large\\ selection\\ of\\ -\\ GPS,\\ GPS\\ sensors,\\ GPS\\ accessories,\\ GPS\\ OEM,\\ PDA,\\ tracking\\ gps,\\ bluetooth\\ gps,\\ fish\\ finders,\\ sounders,\\ cb\\ radios\\ and\\ Walky-talky,\\ flash\\ memory,\\ MP3,\\ radio\\ scanners,\\ digital\\ cameras,\\ car\\ audio\\ and\\ car\\ video,\\ DJ,\\ hand\\ tools,\\ mechanics\\ tools.
vti_charset:SR|windows-1252
