vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|02 Sep 2005 18:49:38 -0000
vti_timecreated:TR|02 Sep 2005 18:49:38 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{A3A490B5-05FB-4D8D-BEB7-081B6485E116}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|02 Sep 2005 18:49:38 -0000
vti_filesize:IR|12607
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
