vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|16 Aug 2005 04:59:00 -0000
vti_timecreated:TR|16 Aug 2005 04:59:00 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{0D7B279B-5428-42D9-A943-CA1BEA91BED1}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|16 Aug 2005 04:59:00 -0000
vti_filesize:IR|4388
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
