vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|16 Aug 2005 04:59:09 -0000
vti_timecreated:TR|16 Aug 2005 04:59:09 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{68EAE648-F170-4C76-80A8-A1F678390BCC}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|16 Aug 2005 04:59:09 -0000
vti_filesize:IR|5438
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
