vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|16 Aug 2005 04:59:24 -0000
vti_timecreated:TR|16 Aug 2005 04:59:24 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{401C875E-6E42-4799-BA51-2F16F44BC0F1}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|16 Aug 2005 04:59:24 -0000
vti_filesize:IR|11644
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
