vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Apr 2005 19:08:15 -0000
vti_extenderversion:SR|5.0.2.6790
vti_title:SR|Sanction - Version (Orange)
vti_lineageid:SR|{D41F4399-347C-4986-B666-020E5E4B7B42}
vti_backlinkinfo:VX|ADMI/MAINT.ASP ADMI/EDITAD.ASP
vti_cacheddtm:TX|14 Apr 2005 19:08:15 -0000
vti_filesize:IR|3673
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" link="#FFBD00" vlink="#FFBD00" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0">
vti_cachedlinkinfo:VX|S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif H|editad.asp S|Simages/blcurve.GIF A|savead.asp
vti_cachedsvcrellinks:VX|FSUS|ADMI/Simages/sanction.gif FHUS|ADMI/sanction.asp FSUS|ADMI/Simages/homegif.GIF FSUS|ADMI/Simages/btcurve.gif FHUS|ADMI/editad.asp FSUS|ADMI/Simages/blcurve.GIF FAUS|ADMI/savead.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
