vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Apr 2005 19:08:17 -0000
vti_extenderversion:SR|5.0.2.6790
vti_title:SR|Sanction - Version (Orange)
vti_lineageid:SR|{A3D1CE76-D67A-44E1-8253-E8EE6EB84485}
vti_backlinkinfo:VX|ADMI/LISTAD.ASP ADMI/MAINT.ASP ADMI/delad.asp ADMI/SBG.ASP
vti_cacheddtm:TX|14 Apr 2005 19:08:17 -0000
vti_filesize:IR|3349
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" link="#FF0000" vlink="#FF0000">
vti_cachedlinkinfo:VX|S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif S|Simages/blcurve.GIF H|newad.asp H|listad.asp
vti_cachedsvcrellinks:VX|FSUS|ADMI/Simages/sanction.gif FHUS|ADMI/sanction.asp FSUS|ADMI/Simages/homegif.GIF FSUS|ADMI/Simages/btcurve.gif FSUS|ADMI/Simages/blcurve.GIF FHUS|ADMI/newad.asp FHUS|ADMI/listad.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
