vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Apr 2005 19:08:34 -0000
vti_extenderversion:SR|5.0.2.6790
vti_title:SR|Sanction - Version Orange
vti_lineageid:SR|{765593C1-9AE2-4BE8-92BD-269E07B813F2}
vti_backlinkinfo:VX|ADMI/NEWAD.ASP ADMI/EDITAD.ASP
vti_cacheddtm:TX|14 Apr 2005 19:08:34 -0000
vti_filesize:IR|1084
vti_cachedtitle:SR|Sanction - Version Orange
vti_cachedbodystyle:SR|<body>
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
