vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Apr 2005 19:08:35 -0000
vti_extenderversion:SR|5.0.2.6790
vti_title:SR|Sanction - Version (Orange)
vti_lineageid:SR|{A4187D0C-9FF1-4597-B22D-1F7D37668DA4}
vti_backlinkinfo:VX|ADMI/SBB.ASP
vti_cacheddtm:TX|14 Apr 2005 19:08:35 -0000
vti_filesize:IR|7823
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" link="#FFffff" vlink="#FFffff">
vti_cachedlinkinfo:VX|A|sbb.asp S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif H|sbbedit.asp H|sbbdel.asp S|Simages/blcurve.GIF
vti_cachedsvcrellinks:VX|FAUS|ADMI/sbb.asp FSUS|ADMI/Simages/sanction.gif FHUS|ADMI/sanction.asp FSUS|ADMI/Simages/homegif.GIF FSUS|ADMI/Simages/btcurve.gif NHUS|ADMI/sbbedit.asp NHUS|ADMI/sbbdel.asp FSUS|ADMI/Simages/blcurve.GIF
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
