<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head>
  <title>ads.inc</title>
</head><body><table style="width: 196px;" 0="">


<tbody><tr>
<td>

<table style="background-color: palegoldenrod; width: 186px; height: 287px;" border="1" cellpadding="5">

<tbody><tr align="left">
<td style="vertical-align: top;">
<a href="http://www.starlite-intl.com/Detail.asp?pid=2221">
<img alt="PDR 150 GPS, Black" src="https://www.starlite-intl.com/Imi/PDR150t.jpg" style="border: 0px solid ; width: 65px;" align="left">
</a>
<font face="Tahoma" size="2">
<i>PDR 150</b></i>, 
3.5" color display, touch screen, preloaded detailed maps of the U.S.A. with "<b>Text-to-Speech</b>" technology.</font><font face="Tahoma" size="2"><small><span style="font-family: Helvetica,Arial,sans-serif;"><big><span style="color: rgb(255, 0, 0);"><span style="color: rgb(0, 0, 0);"></span></span></big></span></small></font>
</td>
</tr>

<tr>
<td align="left">
<a href="http://www.starlite-intl.com/Detail.asp?pid=2222">
<img alt="PDR250 4.3" display="" by="" pharos="" src="https://www.starlite-intl.com/imi/PDR250t.jpg" style="border: 0px solid ; width: 62px;" align="left">
</a>
<font face="Tahoma" size="2">
<i>PDR 250 GPS</i>
Large 4.3&#8221; color display, touch screen, preloaded maps of North America. Detailed street-level navigation, "<b>Text-to-Speech</b>" technology.</font><font face="Tahoma" size="2"><small><span style="font-family: Helvetica,Arial,sans-serif;"><big><span style="color: rgb(255, 0, 0);"><span style="color: rgb(0, 0, 0);"></span></span></big></span></small></font>
</td>
</tr>

<tr align="left">
<td style="vertical-align: top;">
<a href="http://www.starlite-intl.com/Detail.asp?pid=2103&Key=">
<img alt="GPS Smart Phone 600e by Pharos" src="http://www.starlite-intl.com/imi/PTL600et.jpg" style="border: 0px solid ; width: 65px;" align="left">
</a>
<font face="Tahoma" size="2"><i>GPS Phone 600e by Pharos</i>
integrates GPS (Maps not included but available), phone, WiFi, Bluetooth, Windows Mobile Office, Live
Search, digital camera, FM radio, Photo Viewer, MP3 and video player
and much more. <span style="color: rgb(204, 0, 0);">Up to $300.00 Rebate available. </span></font><big><font face="Tahoma" size="2"><span style="font-family: Helvetica,Arial,sans-serif;"><span style="color: rgb(255, 0, 0);"><span style="color: rgb(0, 0, 0);"></span></span></span></font></big><font face="Tahoma" size="2"><small><span style="font-family: Helvetica,Arial,sans-serif;"><span style="color: rgb(0, 153, 0);"> </span></span></small></font><font face="Tahoma" size="2"><small><span style="font-family: Helvetica,Arial,sans-serif;"><big><span style="color: rgb(255, 0, 0);"><span style="color: rgb(0, 0, 0);"></span></span></big></span></small></font>
</td>
</tr>

<tr align="left">
<td style="vertical-align: top;">
<a href="http://www.starlite-intl.com/Detail.asp?pid=2368&Key=">
<img alt="Streetpilot c340 RB by Garmin" src="http://www.starlite-intl.com/imi/SPC340t.jpg" style="border: 0px solid ; width: 65px;" align="left">
</a>
<font face="Tahoma" size="2"><b>Streetpilot c340 RB</b> GPS by Garmin, REFURBISHED. <b>Text to Speach</b> capable announce names of streets. 
Preloaded maps for the U.S. and Canada. 3.5" <b>touch screen LCD display</b>
</font>
</td>
</tr>

<tr align="left">
<td style="vertical-align: top;">
<a href="http://www.starlite-intl.com/Detail.asp?pid=2116&amp;Key=">
<img alt="Astro GPS Dog tracking by Garmin" src="https://www.starlite-intl.com/Imi/astrot.jpg" style="border: 0px solid ; width: 64px;" align="left">
</a>
<font face="Tahoma" size="2">
<i>Astro by Garmin, </i>
GPS enabled <b>dog tracking</b> system for hunters and sportsmen. Pinpoints your dog&#8217;s position and shows you exactly where he is.
</font>
</td>
</tr>

<tr align="left">
<td style="vertical-align: top;">
<a href="http://www.starlite-intl.com/Detail.asp?pid=2209&amp;Key=">
<img alt="Nuvi 760 GPS by Garmin" src="https://www.starlite-intl.com/imi/Nuvi760t.gif" style="border: 0px solid ; width: 65px;" align="left">
</a>
<font face="Tahoma" size="2">
<i>Nuvi 760 GPS by Garmin</i>
Widescreen display, preloaded North America maps, FM transmitter,
hands-free calling, traffic alerts, Text-to Speech, route planning, <b>multiple destinations</b> and much more
</font>
</td>
</tr>


</tbody></table>

</td>
</tr>


</tbody></table></body></html>