vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|06 Feb 2009 03:16:20 -0000
vti_timecreated:TR|26 Feb 2006 00:46:00 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{A8B76E4E-D9E0-4465-91CC-87C7241858F5}
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|26 Feb 2006 00:46:00 -0000
vti_cacheddtm:TX|26 Feb 2006 00:46:00 -0000
vti_filesize:IR|5438
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
