vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|06 Feb 2009 03:16:21 -0000
vti_timecreated:TR|26 Feb 2006 00:46:08 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{E174ACDE-8D38-40AA-AB7A-248F05F730BD}
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|26 Feb 2006 00:46:08 -0000
vti_cacheddtm:TX|26 Feb 2006 00:46:08 -0000
vti_filesize:IR|26842
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
