vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|06 Feb 2009 03:16:21 -0000
vti_timecreated:TR|26 Feb 2006 00:46:10 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{B1119DC9-11F1-4E6D-9FDC-1E8D3CDF1478}
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|26 Feb 2006 00:46:10 -0000
vti_cacheddtm:TX|26 Feb 2006 00:46:10 -0000
vti_filesize:IR|10043
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
