<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head>
  <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
  <title>ads.inc</title>
</head><body><br>

<table border="0" bordercolor="black" width="85%">

<tbody><tr>
<td>

	<table bgcolor="palegoldenrod" cellpadding="5" border="0">
	<tbody><tr>
	    <td align="center"><span style="font-family: helvetica,arial,sans-serif;">
	    eCommerce <big><span style="color: rgb(0, 0, 153);">website design</span></big>. 
	    Your first year of web hosting is 
	    </span>
	    <font color="brown" style="font-family: helvetica,arial,sans-serif;">FREE</font><span style="font-family: helvetica,arial,sans-serif;">.
	    </span><a href="mailto:starlite@starlite-intl.com" style="font-family: helvetica,arial,sans-serif;">Email us</a>
	    <span style="font-family: helvetica,arial,sans-serif;"> for details.<br>
</span>
            <hr style="width: 100%; height: 2px;"></td>
	</tr><tr align="center">
	      <td style="vertical-align: top;">
	    <a href="http://www.starlite-intl.com/scart/scart.asp?sar=Certificates&amp;area=Gift%20Certificates&amp;sid=257">
	      <img src="https://www.starlite-intl.com/imi/GCAD.jpg" style="border: 0px solid ; width: 170px; height: 85px;" title="" alt="Gift Certificate" align="middle">
	      </a>
	      </td>
	    </tr>

	</tbody></table>

</td>
</tr>


</tbody>
</table>
</body></html>