vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Apr 2005 19:08:18 -0000
vti_extenderversion:SR|5.0.2.6790
vti_title:SR|Sanction - Version (Orange)
vti_lineageid:SR|{76ABC77A-ABC5-4F8D-91CA-356E7A867253}
vti_backlinkinfo:VX|ADMI/NEWAD.ASP ADMI/SBG.ASP
vti_cacheddtm:TX|14 Apr 2005 19:08:18 -0000
vti_filesize:IR|2668
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" link="#FFffff" vlink="#FFffff">
vti_cachedlinkinfo:VX|S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif S|Simages/blcurve.GIF H|newad.asp A|editad.asp H|listad.asp
vti_cachedsvcrellinks:VX|FSUS|ADMI/Simages/sanction.gif FHUS|ADMI/sanction.asp FSUS|ADMI/Simages/homegif.GIF FSUS|ADMI/Simages/btcurve.gif FSUS|ADMI/Simages/blcurve.GIF FHUS|ADMI/newad.asp FAUS|ADMI/editad.asp FHUS|ADMI/listad.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
