vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Apr 2005 19:08:35 -0000
vti_extenderversion:SR|5.0.2.6790
vti_title:SR|Sanction - Version (Orange)
vti_lineageid:SR|{FCBBCD16-A18A-4A80-A28C-5A3E9C7FA572}
vti_backlinkinfo:VX|ADMI/Sanction.asp
vti_cacheddtm:TX|14 Apr 2005 19:08:35 -0000
vti_filesize:IR|2073
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" link="#FFffff" vlink="#FFffff">
vti_cachedlinkinfo:VX|S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif S|Simages/blcurve.GIF H|maint.asp H|newad.asp H|listad.asp H|delad.asp
vti_cachedsvcrellinks:VX|FSUS|ADMI/Simages/sanction.gif FHUS|ADMI/sanction.asp FSUS|ADMI/Simages/homegif.GIF FSUS|ADMI/Simages/btcurve.gif FSUS|ADMI/Simages/blcurve.GIF FHUS|ADMI/maint.asp FHUS|ADMI/newad.asp FHUS|ADMI/listad.asp FHUS|ADMI/delad.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
