vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Apr 2005 19:08:37 -0000
vti_extenderversion:SR|5.0.2.6790
vti_title:SR|SANCTION: USER ADMINISTRATION TOOL - C.1999 - DESIGNWERX
vti_lineageid:SR|{9B5EE99B-2CC3-45FC-8020-11DF90CC55B7}
vti_backlinkinfo:VX|ADMI/Sclass1.asp
vti_cacheddtm:TX|14 Apr 2005 19:08:37 -0000
vti_filesize:IR|808
vti_cachedtitle:SR|SANCTION: USER ADMINISTRATION TOOL - C.1999 - DESIGNWERX
vti_cachedbodystyle:SR|<body bgcolor="#000000" TOPMARGIN="5" LEFTMARGIN="5" LINK="#E00000" VLINK="#E00000">
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
