vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|28 Jul 2006 02:52:09 -0000
vti_timecreated:TR|28 Jul 2006 02:52:09 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{C5AE22D3-F516-405C-B59A-BE5FF96E2D0F}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|28 Jul 2006 02:52:09 -0000
vti_filesize:IR|8954
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
