vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:24:57 -0000
vti_timecreated:TR|06 Mar 2006 03:25:09 -0000
vti_title:SR|Sanction - Version Orange
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{FFA647F7-1A5E-4FA0-8E74-45086F2EFE59}
vti_backlinkinfo:VX|ADMI/BKPs/Bkp.060305/NEWAD.ASP ADMI/BKPs/Bkp.060305/EDITAD.ASP
vti_nexttolasttimemodified:TR|06 Mar 2006 03:25:09 -0000
vti_cacheddtm:TX|06 Mar 2006 03:25:09 -0000
vti_filesize:IR|1084
vti_cachedtitle:SR|Sanction - Version Orange
vti_cachedbodystyle:SR|<body>
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
