vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:24:57 -0000
vti_timecreated:TR|06 Mar 2006 03:25:10 -0000
vti_title:SR|Sanction - Version (Orange)
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{3D60F73F-8045-4161-B35F-FC3281D39DAE}
vti_backlinkinfo:VX|ADMI/BKPs/Bkp.060305/SBB.ASP
vti_nexttolasttimemodified:TR|06 Mar 2006 03:25:10 -0000
vti_cacheddtm:TX|06 Mar 2006 03:25:10 -0000
vti_filesize:IR|7823
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" link="#FFffff" vlink="#FFffff">
vti_cachedlinkinfo:VX|A|sbb.asp S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif H|sbbedit.asp H|sbbdel.asp S|Simages/blcurve.GIF
vti_cachedsvcrellinks:VX|FAUS|ADMI/BKPs/Bkp.060305/sbb.asp NSUS|ADMI/BKPs/Bkp.060305/Simages/sanction.gif FHUS|ADMI/BKPs/Bkp.060305/sanction.asp NSUS|ADMI/BKPs/Bkp.060305/Simages/homegif.GIF NSUS|ADMI/BKPs/Bkp.060305/Simages/btcurve.gif NHUS|ADMI/BKPs/Bkp.060305/sbbedit.asp NHUS|ADMI/BKPs/Bkp.060305/sbbdel.asp NSUS|ADMI/BKPs/Bkp.060305/Simages/blcurve.GIF
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
