vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|28 Jul 2006 02:51:37 -0000
vti_timecreated:TR|28 Jul 2006 02:51:37 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{E8F04EDC-9D60-46E9-B979-78F356701494}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|28 Jul 2006 02:51:37 -0000
vti_filesize:IR|4388
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
