vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|28 Jul 2006 02:51:47 -0000
vti_timecreated:TR|28 Jul 2006 02:51:47 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{5E7915D4-33EA-4434-80D9-61C98779B377}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|28 Jul 2006 02:51:47 -0000
vti_filesize:IR|5438
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
