vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|28 Jul 2006 02:51:59 -0000
vti_timecreated:TR|28 Jul 2006 02:51:59 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{5BCE2838-11E3-484D-B2AB-AF73CF57576F}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|28 Jul 2006 02:51:59 -0000
vti_filesize:IR|26842
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
