vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:25:05 -0000
vti_timecreated:TR|23 Feb 2006 16:52:58 -0000
vti_title:SR|Sanction - Version (Orange)
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{BADEF626-7B68-425A-A271-D4559017A1EA}
vti_backlinkinfo:VX|ADMI/BKPs/Bkp.060223/MAINT.ASP ADMI/BKPs/Bkp.060223/EDITAD.ASP
vti_nexttolasttimemodified:TR|23 Feb 2006 16:52:58 -0000
vti_cacheddtm:TX|23 Feb 2006 16:52:58 -0000
vti_filesize:IR|3673
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" link="#FFBD00" vlink="#FFBD00" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0">
vti_cachedlinkinfo:VX|S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif H|editad.asp S|Simages/blcurve.GIF A|savead.asp
vti_cachedsvcrellinks:VX|NSUS|ADMI/BKPs/Bkp.060223/Simages/sanction.gif FHUS|ADMI/BKPs/Bkp.060223/sanction.asp NSUS|ADMI/BKPs/Bkp.060223/Simages/homegif.GIF NSUS|ADMI/BKPs/Bkp.060223/Simages/btcurve.gif FHUS|ADMI/BKPs/Bkp.060223/editad.asp NSUS|ADMI/BKPs/Bkp.060223/Simages/blcurve.GIF FAUS|ADMI/BKPs/Bkp.060223/savead.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
