vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:25:05 -0000
vti_timecreated:TR|23 Feb 2006 16:53:15 -0000
vti_title:SR|Sanction - Version Orange
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{2B4985A9-0F80-474A-92E1-1D0403713A9F}
vti_backlinkinfo:VX|ADMI/BKPs/Bkp.060223/EDITAD.ASP ADMI/BKPs/Bkp.060223/NEWAD.ASP
vti_nexttolasttimemodified:TR|23 Feb 2006 16:53:15 -0000
vti_cacheddtm:TX|23 Feb 2006 16:53:15 -0000
vti_filesize:IR|1084
vti_cachedtitle:SR|Sanction - Version Orange
vti_cachedbodystyle:SR|<body>
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
