vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:25:05 -0000
vti_timecreated:TR|23 Feb 2006 16:53:15 -0000
vti_title:SR|Sanction - Version (Orange)
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{4D0E4A17-3FC7-4517-93AA-31FA208B4462}
vti_backlinkinfo:VX|ADMI/BKPs/Bkp.060223/SBB.ASP
vti_nexttolasttimemodified:TR|23 Feb 2006 16:53:15 -0000
vti_cacheddtm:TX|23 Feb 2006 16:53:15 -0000
vti_filesize:IR|7823
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" link="#FFffff" vlink="#FFffff">
vti_cachedlinkinfo:VX|A|sbb.asp S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif H|sbbedit.asp H|sbbdel.asp S|Simages/blcurve.GIF
vti_cachedsvcrellinks:VX|FAUS|ADMI/BKPs/Bkp.060223/sbb.asp NSUS|ADMI/BKPs/Bkp.060223/Simages/sanction.gif FHUS|ADMI/BKPs/Bkp.060223/sanction.asp NSUS|ADMI/BKPs/Bkp.060223/Simages/homegif.GIF NSUS|ADMI/BKPs/Bkp.060223/Simages/btcurve.gif NHUS|ADMI/BKPs/Bkp.060223/sbbedit.asp NHUS|ADMI/BKPs/Bkp.060223/sbbdel.asp NSUS|ADMI/BKPs/Bkp.060223/Simages/blcurve.GIF
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
