vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:25:04 -0000
vti_timecreated:TR|23 Feb 2006 16:53:16 -0000
vti_title:SR|Sanction - Version (Orange)
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{FE1BEA3F-01FD-4A15-90FF-F20A30B9BDE9}
vti_backlinkinfo:VX|ADMI/BKPs/Bkp.060223/Sanction.asp
vti_nexttolasttimemodified:TR|23 Feb 2006 16:53:16 -0000
vti_cacheddtm:TX|23 Feb 2006 16:53:16 -0000
vti_filesize:IR|2073
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" link="#FFffff" vlink="#FFffff">
vti_cachedlinkinfo:VX|S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif S|Simages/blcurve.GIF H|maint.asp H|newad.asp H|listad.asp H|delad.asp
vti_cachedsvcrellinks:VX|NSUS|ADMI/BKPs/Bkp.060223/Simages/sanction.gif FHUS|ADMI/BKPs/Bkp.060223/sanction.asp NSUS|ADMI/BKPs/Bkp.060223/Simages/homegif.GIF NSUS|ADMI/BKPs/Bkp.060223/Simages/btcurve.gif NSUS|ADMI/BKPs/Bkp.060223/Simages/blcurve.GIF FHUS|ADMI/BKPs/Bkp.060223/maint.asp FHUS|ADMI/BKPs/Bkp.060223/newad.asp FHUS|ADMI/BKPs/Bkp.060223/listad.asp FHUS|ADMI/BKPs/Bkp.060223/delad.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
