vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:25:05 -0000
vti_timecreated:TR|23 Feb 2006 16:53:18 -0000
vti_title:SR|SANCTION: USER ADMINISTRATION TOOL - C.1999 - DESIGNWERX
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{8D3CB06F-7BB7-4FCB-BADC-BA4A62459C82}
vti_backlinkinfo:VX|ADMI/BKPs/Bkp.060223/Sclass1.asp
vti_nexttolasttimemodified:TR|23 Feb 2006 16:53:18 -0000
vti_cacheddtm:TX|23 Feb 2006 16:53:18 -0000
vti_filesize:IR|808
vti_cachedtitle:SR|SANCTION: USER ADMINISTRATION TOOL - C.1999 - DESIGNWERX
vti_cachedbodystyle:SR|<body bgcolor="#000000" TOPMARGIN="5" LEFTMARGIN="5" LINK="#E00000" VLINK="#E00000">
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
