vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:24:43 -0000
vti_timecreated:TR|07 Mar 2006 06:46:43 -0000
vti_title:SR|Sanction - Version (Orange)
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{F68A0F89-B370-46F6-9262-B05124C83D9E}
vti_backlinkinfo:VX|ADMI/BKPs/Bkp.060306/NEWAD.ASP ADMI/BKPs/Bkp.060306/SBG.ASP
vti_nexttolasttimemodified:TR|07 Mar 2006 06:46:43 -0000
vti_cacheddtm:TX|07 Mar 2006 06:46:43 -0000
vti_filesize:IR|2668
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" link="#FFffff" vlink="#FFffff">
vti_cachedlinkinfo:VX|S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif S|Simages/blcurve.GIF H|newad.asp A|editad.asp H|listad.asp
vti_cachedsvcrellinks:VX|NSUS|ADMI/BKPs/Bkp.060306/Simages/sanction.gif FHUS|ADMI/BKPs/Bkp.060306/sanction.asp NSUS|ADMI/BKPs/Bkp.060306/Simages/homegif.GIF NSUS|ADMI/BKPs/Bkp.060306/Simages/btcurve.gif NSUS|ADMI/BKPs/Bkp.060306/Simages/blcurve.GIF FHUS|ADMI/BKPs/Bkp.060306/newad.asp FAUS|ADMI/BKPs/Bkp.060306/editad.asp FHUS|ADMI/BKPs/Bkp.060306/listad.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
