vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:24:43 -0000
vti_timecreated:TR|07 Mar 2006 06:46:58 -0000
vti_title:SR|Sanction - Version Orange
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{8A2B0AE6-95C1-482E-8D6A-A139F3ED2E1B}
vti_backlinkinfo:VX|ADMI/BKPs/Bkp.060306/NEWAD.ASP ADMI/BKPs/Bkp.060306/EDITAD.ASP
vti_nexttolasttimemodified:TR|07 Mar 2006 06:46:58 -0000
vti_cacheddtm:TX|07 Mar 2006 06:46:58 -0000
vti_filesize:IR|1084
vti_cachedtitle:SR|Sanction - Version Orange
vti_cachedbodystyle:SR|<body>
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
