vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:24:43 -0000
vti_timecreated:TR|07 Mar 2006 06:46:59 -0000
vti_title:SR|Sanction - Version (Orange)
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{CBA4E92E-6028-453F-8E70-F1160E2BD6BB}
vti_backlinkinfo:VX|ADMI/BKPs/Bkp.060306/Sanction.asp ADMI/BKPs/Bkp.060306/Sanction.BKP.asp
vti_nexttolasttimemodified:TR|07 Mar 2006 06:46:59 -0000
vti_cacheddtm:TX|07 Mar 2006 06:46:59 -0000
vti_filesize:IR|2073
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" link="#FFffff" vlink="#FFffff">
vti_cachedlinkinfo:VX|S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif S|Simages/blcurve.GIF H|maint.asp H|newad.asp H|listad.asp H|delad.asp
vti_cachedsvcrellinks:VX|NSUS|ADMI/BKPs/Bkp.060306/Simages/sanction.gif FHUS|ADMI/BKPs/Bkp.060306/sanction.asp NSUS|ADMI/BKPs/Bkp.060306/Simages/homegif.GIF NSUS|ADMI/BKPs/Bkp.060306/Simages/btcurve.gif NSUS|ADMI/BKPs/Bkp.060306/Simages/blcurve.GIF FHUS|ADMI/BKPs/Bkp.060306/maint.asp FHUS|ADMI/BKPs/Bkp.060306/newad.asp FHUS|ADMI/BKPs/Bkp.060306/listad.asp FHUS|ADMI/BKPs/Bkp.060306/delad.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
