vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:24:43 -0000
vti_timecreated:TR|07 Mar 2006 06:47:01 -0000
vti_title:SR|SANCTION: USER ADMINISTRATION TOOL - C.1999 - DESIGNWERX
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{BF4A8855-7A74-4FD5-9387-13E920946D1E}
vti_backlinkinfo:VX|ADMI/BKPs/Bkp.060306/Sclass1.asp
vti_nexttolasttimemodified:TR|07 Mar 2006 06:47:01 -0000
vti_cacheddtm:TX|07 Mar 2006 06:47:01 -0000
vti_filesize:IR|808
vti_cachedtitle:SR|SANCTION: USER ADMINISTRATION TOOL - C.1999 - DESIGNWERX
vti_cachedbodystyle:SR|<body bgcolor="#000000" TOPMARGIN="5" LEFTMARGIN="5" LINK="#E00000" VLINK="#E00000">
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
