vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:12:47 -0000
vti_timecreated:TR|05 Mar 2006 23:57:41 -0000
vti_title:SR|Starlite-intl.com - GPS, tracking GPS, cb radios, flash memory, audio/video, marine radios, fish finders, hand tools
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{3F33CEF5-67A6-409C-BF7D-1AF8DB7430AD}
vti_backlinkinfo:VX|SCART/BKPs/Dead/Bkp.060305/07102005SCARTstart.ASP
vti_nexttolasttimemodified:TR|05 Mar 2006 23:57:41 -0000
vti_cacheddtm:TX|05 Mar 2006 23:57:41 -0000
vti_filesize:IR|5781
vti_cachedtitle:SR|Starlite-intl.com - GPS, tracking GPS, cb radios, flash memory, audio/video, marine radios, fish finders, hand tools
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" link="#000000" vlink="#000000" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0">
vti_cachedlinkinfo:VX|Q|../Misc/StyleSheet1.css S|../Images/can1.gif S|../Images/USA1.gif K|07102005SCARTstart.ASP
vti_cachedsvcrellinks:VX|NQUS|SCART/BKPs/Dead/Misc/StyleSheet1.css NSUS|SCART/BKPs/Dead/Images/can1.gif NSUS|SCART/BKPs/Dead/Images/USA1.gif FKUS|SCART/BKPs/Dead/Bkp.060305/07102005SCARTstart.ASP
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|keywords GPS,Navigation,Garmin,CB-Radios,Flush\\ memory,Uniden,Cobra,Motorola,2-way\\ radios,Hand-tools,Pyramid\\  description Online\\ store\\ for\\ GPS,\\ Global\\ Positioning\\ Systems,\\ Navigation\\ equipment,\\ CB\\ Radios,\\ FRS\\ Radios,\\ GMRS\\ Radios,\\ Antennas,\\ Car\\ Audio,\\ Hand\\ Tools.\\ \\ Shopping\\ on\\ a\\ secure\\ SSL\\ line.\\ Accepting\\ Visa,\\ Mastercard,\\ American\\ Express\\ cards,\\ PayPal.
vti_charset:SR|windows-1252
