vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:12:46 -0000
vti_timecreated:TR|05 Mar 2006 23:57:58 -0000
vti_lineageid:SR|{C087BF5E-DF3D-4251-AE38-CD7F910757FC}
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|05 Mar 2006 23:57:58 -0000
vti_cacheddtm:TX|05 Mar 2006 23:57:58 -0000
vti_filesize:IR|2196
