vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|16 Aug 2005 04:59:11 -0000
vti_timecreated:TR|16 Aug 2005 04:59:11 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{77D389C7-3341-4AFA-89D9-B3A8201F1619}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|16 Aug 2005 04:59:11 -0000
vti_filesize:IR|11391
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
