vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|29 Apr 2005 04:31:37 -0000
vti_timecreated:TR|29 Apr 2005 04:31:37 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{338714F0-9135-4F97-B0C0-3F1B825EE4F5}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|29 Apr 2005 04:31:37 -0000
vti_filesize:IR|4388
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
