vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|29 Apr 2005 04:31:45 -0000
vti_timecreated:TR|29 Apr 2005 04:31:45 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{B8A00A52-4CC1-4E2F-B17C-42A9A22A24A0}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|29 Apr 2005 04:31:45 -0000
vti_filesize:IR|12607
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
