<% If True Then %>

	<% If FALSE Then %>
	<table style="border:0px solid green; background-color:blue;"  align='center' width=<%=PageWidth%> >		<% ' Start Table Footer 1 %>

	<tr>
		<td align="center">
		<table align="center"><tr><td>
		<%
		If TRUE Then 
		%>
		<!-- 
		Suckerfish drop-down menus ...
		#INCLUDE VIRTUAL = "mobile0/Misc/Navbars/navbar1bFooter.inc.asp"
		--> 
		<% End If %>
		</td></tr></table>

		<XXXimg align="center" src="https://www.starlite-intl.com/Images/bottompage2.GIF" height="43px">
		</td>
	</tr>

	</table>	<% ' End Table Footer 1 %>   
	<% End If %>

	<span style="text-decoration:none;font-size:8pt;">
	Website by IntelliGineering.com
	</span>

	<br><br>  	   
<% End If %>