vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 22:25:09 -0000
vti_timecreated:TR|06 Mar 2006 03:20:39 -0000
vti_title:SR|Sanction - Version (Orange)
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{AB62A5BF-4878-4CD2-A5BE-1C4E593CFFCC}
vti_backlinkinfo:VX|ADMI/BKPs/Dead/Bkp.060305/EDITAD.ASP
vti_nexttolasttimemodified:TR|06 Mar 2006 03:24:02 -0000
vti_cacheddtm:TX|06 Mar 2006 03:20:39 -0000
vti_filesize:IR|3673
vti_cachedtitle:SR|Sanction - Version (Orange)
vti_cachedbodystyle:SR|<body bgcolor="#000000" text="#FFFFFF" link="#FFBD00" vlink="#FFBD00" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0">
vti_cachedlinkinfo:VX|S|Simages/sanction.gif H|sanction.asp S|Simages/homegif.GIF S|Simages/btcurve.gif H|editad.asp S|Simages/blcurve.GIF A|savead.asp
vti_cachedsvcrellinks:VX|NSUS|ADMI/BKPs/Dead/Bkp.060305/Simages/sanction.gif NHUS|ADMI/BKPs/Dead/Bkp.060305/sanction.asp NSUS|ADMI/BKPs/Dead/Bkp.060305/Simages/homegif.GIF NSUS|ADMI/BKPs/Dead/Bkp.060305/Simages/btcurve.gif FHUS|ADMI/BKPs/Dead/Bkp.060305/editad.asp NSUS|ADMI/BKPs/Dead/Bkp.060305/Simages/blcurve.GIF NAUS|ADMI/BKPs/Dead/Bkp.060305/savead.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
