vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|20 Nov 2006 23:43:24 -0000
vti_timecreated:TR|23 Feb 2006 03:13:06 -0000
vti_lineageid:SR|{983C08C1-B58C-4AA1-BF5C-21DBBDB5E153}
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|22 Feb 2006 22:13:06 -0500
vti_cacheddtm:TX|23 Feb 2006 03:13:06 -0000
vti_filesize:IR|6822
