vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|20 Nov 2006 23:43:26 -0000
vti_timecreated:TR|23 Feb 2006 17:09:16 -0000
vti_lineageid:SR|{33DAC190-2F1D-4864-BE8A-C6BF6765921E}
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|26 Feb 2006 13:29:15 -0500
vti_cacheddtm:TX|26 Feb 2006 04:18:15 -0000
vti_filesize:IR|3598
