<a href="../help.asp" onmouseout="msout(0,0)"
onmouseover="msover(0,0)"><img
                src="../Images/question1.gif" alt="Help" border="0"
                width="25" height="29"></a><a
                href="./scart.asp?action=viewcart&amp;pid=0&amp;sid=11&amp;" onmouseout="msout(1,1)"
onmouseover="msover(1,1)"><img
                src="../Images/scart1.gif" alt="Shopping Cart"
                border="0" width="33" height="29"></a><a
                href="Http://www.starlite-intl.com/index.asp" onmouseout="msout(2,2)"
onmouseover="msover(2,2)"><img src="../Images/home1.gif"
                alt="Home" border="0" width="23" height="29"></a><a
                href="./scart.asp?pid=0&amp;sid=11&amp;area=New!&amp;sar=New%20Products" onmouseout="msout(3,3)"
onmouseover="msover(3,3)"><img
                src="../Images/new1.gif" alt="New Products"
                border="0" width="29" height="29"></a><a
                href="./scartstart.asp?pid=0&amp;sid=11&amp;area=Specialx&amp;sar=Specialx" onmouseout="msout(4,4)"
onmouseover="msover(4,4)"><img src="../Images/cat1.gif"
                alt="Online Catalogue" border="0" width="26"
                height="29"></a><a
                href="./scartstart.asp?pid=0&amp;sid=11&amp;area=Specials&amp;sar=Specials" onmouseout="msout(5,5)"
onmouseover="msover(5,5)"><img
                src="../Images/ex1.gif" alt="Specials" border="0"
                width="28" height="29"></a>