vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|26 Mar 2010 02:45:41 -0000
vti_timecreated:TR|29 Apr 2005 04:31:37 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{2E419219-C96E-4A3D-BAAD-A18A71DE4D78}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|26 Mar 2010 02:45:41 -0000
vti_filesize:IR|6139
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
