vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|29 Apr 2005 04:31:40 -0000
vti_timecreated:TR|29 Apr 2005 04:31:40 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{23D63859-959D-4268-B648-E7D161AD45E0}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|29 Apr 2005 04:31:40 -0000
vti_filesize:IR|12259
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
