vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|29 Apr 2005 04:31:42 -0000
vti_timecreated:TR|29 Apr 2005 04:31:42 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{7CAA401D-C4BF-4E5C-8CEB-A9FA41104FC1}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|29 Apr 2005 04:31:42 -0000
vti_filesize:IR|5438
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
