vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|24 Mar 2010 08:37:35 -0000
vti_timecreated:TR|29 Apr 2005 04:31:47 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{538A4BAE-2E97-48F5-B358-BAA8C2A97E33}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|24 Mar 2010 08:37:35 -0000
vti_filesize:IR|28056
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
