vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|29 Apr 2005 04:31:51 -0000
vti_timecreated:TR|29 Apr 2005 04:31:51 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{7861AA92-9AF6-41C4-B96D-C00410E7E149}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|29 Apr 2005 04:31:51 -0000
vti_filesize:IR|10043
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
