vti_encoding:SR|utf8-nl
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_timelastmodified:TR|02 Sep 2005 18:49:24 -0000
vti_timecreated:TR|02 Sep 2005 18:49:24 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{81EC3BD0-E17D-4494-9B78-F7F61322B412}
vti_backlinkinfo:VX|
vti_cacheddtm:TX|02 Sep 2005 18:49:24 -0000
vti_filesize:IR|4388
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
