vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|20 Nov 2006 23:46:31 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{0CD31CE8-F74A-4730-9C8A-53E1CFD67990}
vti_backlinkinfo:VX|
vti_author:SR|ADONIS\\starliteintlcom
vti_modifiedby:SR|ADONIS\\starliteintlcom
vti_nexttolasttimemodified:TW|03 Nov 2005 23:10:22 -0500
vti_timecreated:TR|22 Aug 2005 06:31:56 -0000
vti_cacheddtm:TX|22 Aug 2005 06:32:14 -0000
vti_filesize:IR|3812
